'use client';

import { useEffect, useMemo, useState } from 'react';
import {
  Activity,
  ArrowRightLeft,
  ClipboardCheck,
  Code2,
  Files,
  FileSearch,
  GitBranch,
  GitPullRequest,
  ListTodo,
  MessagesSquare,
  PanelBottomOpen,
  Settings,
  Terminal,
} from 'lucide-react';
import { SiGithub } from 'react-icons/si';

import { getCommandFavoritesStore } from '../../lib/commandFavoritesStore';
import type { CommandItem } from './types';

export type SettingsTab = 'setup' | 'team' | 'machine' | 'agents' | 'workspaces' | 'integrations';

interface UseCommandPaletteCommandsProps {
  onOpenSettings: (tab: SettingsTab) => void;
  onOpenEventStream: () => void;
  onOpenGitPanel: () => void;
  onOpenBacklog: () => void;
  onOpenPendingReview: () => void;
  /** Navigation callbacks */
  onOpenChatroomSwitcher: () => void;
  onOpenFileSelector: () => void;
  /** Workspace action callbacks — conditionally available (legacy single-workspace) */
  onOpenInVSCode?: (() => void) | null;
  onOpenInGitHubDesktop?: (() => void) | null;
  onOpenPROnGitHub?: (() => void) | null;
  onOpenPRReview?: (() => void) | null;
  onViewGitHubPullRequests?: (() => void) | null;
  onViewGitHubRepository?: (() => void) | null;
  onOpenWorkspaceDetails?: (() => void) | null;
  /** Runnable commands for matching favorites to scripts */
  runnableCommands?: Array<{ name: string; script: string; source: string }>;
  /** Callback to open the Process Manager with a specific command selected */
  onOpenProcessManagerWithCommand?: (commandName: string) => void;
  /** Callback to directly execute a command (run + open terminal) */
  onRunCommand?: (commandName: string, script: string) => void;
  /** Callback to open the Process Manager */
  onOpenProcessManager?: () => void;
  /** Callback to switch to Explorer view */
  onShowExplorer?: (() => void) | null;
  /** Callback to switch to Messages view */
  onShowMessages?: () => void;
  /**
   * Per-workspace command items generated by WorkspaceCommandsAggregator.
   * When provided, these replace the legacy single-workspace action commands
   * (onOpenInVSCode, onOpenInGitHubDesktop, etc.).
   */
  workspaceCommands?: CommandItem[];
}

/**
 * Hook that builds the list of commands for the command palette.
 *
 * Provides panel navigation commands and workspace action commands.
 * Action commands are conditionally included based on workspace availability.
 */
export function useCommandPaletteCommands({
  onOpenSettings,
  onOpenEventStream,
  onOpenGitPanel,
  onOpenBacklog,
  onOpenPendingReview,
  onOpenChatroomSwitcher,
  onOpenFileSelector,
  onOpenInVSCode,
  onOpenInGitHubDesktop,
  onOpenPROnGitHub,
  onOpenPRReview,
  onViewGitHubPullRequests,
  onViewGitHubRepository,
  onOpenWorkspaceDetails,
  runnableCommands,
  onOpenProcessManagerWithCommand,
  onRunCommand,
  onOpenProcessManager,
  onShowExplorer,
  onShowMessages,
  workspaceCommands,
}: UseCommandPaletteCommandsProps): CommandItem[] {
  // Track favorites changes from Process Manager via custom event
  const [favoritesVersion, setFavoritesVersion] = useState(0);
  useEffect(() => {
    const handler = () => setFavoritesVersion((v) => v + 1);
    window.addEventListener('chatroom:favorites-changed', handler);
    return () => window.removeEventListener('chatroom:favorites-changed', handler);
  }, []);

  return useMemo<CommandItem[]>(() => {
    const commands: CommandItem[] = [];

    // ─── Favorites (favourited commands from process manager) ────────
    if (runnableCommands && (onRunCommand || onOpenProcessManagerWithCommand)) {
      const favoritesStore = getCommandFavoritesStore();
      const favorites = favoritesStore.getAll();

      for (const cmd of runnableCommands) {
        if (favorites.has(cmd.name)) {
          commands.push({
            id: `fav-${cmd.name}`,
            label: cmd.name,
            icon: <Terminal size={14} />,
            category: 'Commands',
            action: () => {
              if (onRunCommand) {
                onRunCommand(cmd.name, cmd.script);
              } else if (onOpenProcessManagerWithCommand) {
                onOpenProcessManagerWithCommand(cmd.name);
              }
            },
          });
        }
      }
    }

    // ─── Navigate (shown first) ──────────────────────────
    commands.push(
      {
        id: 'nav-switch-chatroom',
        label: 'Chatroom: Switch Chatroom',
        icon: <ArrowRightLeft size={14} />,
        category: 'Navigate',
        shortcut: '⌘K',
        action: onOpenChatroomSwitcher,
      },
      {
        id: 'nav-go-to-file',
        label: 'Chatroom: Go to File',
        icon: <FileSearch size={14} />,
        category: 'Navigate',
        shortcut: '⌘P',
        action: onOpenFileSelector,
      }
    );

    // ─── Workspace Actions ────────────────────────────────
    // When workspaceCommands is provided (multi-workspace mode), use those.
    // Otherwise fall back to legacy single-workspace callbacks.
    if (workspaceCommands && workspaceCommands.length > 0) {
      commands.push(...workspaceCommands);
    } else {
      // Legacy single-workspace commands (backward compatible)
      if (onOpenInVSCode) {
        commands.push({
          id: 'action-open-vscode',
          label: 'Machine: Open in VS Code',
          icon: <Code2 size={14} />,
          category: 'Actions',
          action: onOpenInVSCode,
        });
      }

      if (onOpenInGitHubDesktop) {
        commands.push({
          id: 'action-open-github-desktop',
          label: 'Machine: Open in GitHub Desktop',
          icon: <SiGithub size={14} />,
          category: 'Actions',
          action: onOpenInGitHubDesktop,
        });
      }

      if (onViewGitHubPullRequests) {
        commands.push({
          id: 'action-view-github-prs',
          label: 'Github: View Pull Requests',
          icon: <SiGithub size={14} />,
          category: 'Actions',
          keywords: ['PR', 'PRs'],
          action: onViewGitHubPullRequests,
        });
      }

      if (onViewGitHubRepository) {
        commands.push({
          id: 'action-view-github-repo',
          label: 'Github: View Repository',
          icon: <SiGithub size={14} />,
          category: 'Actions',
          keywords: ['repo', 'repository', 'github'],
          action: onViewGitHubRepository,
        });
      }

      if (onOpenPROnGitHub) {
        commands.push({
          id: 'action-open-pr-github',
          label: 'Github: View Current PR',
          icon: <GitPullRequest size={14} />,
          category: 'Actions',
          keywords: ['PR'],
          action: onOpenPROnGitHub,
        });
      }

      if (onOpenPRReview) {
        commands.push({
          id: 'action-pr-review-diff',
          label: 'Chatroom: Review Pull Requests',
          icon: <GitPullRequest size={14} />,
          category: 'Actions',
          keywords: ['PR', 'PRs', 'Review'],
          action: onOpenPRReview,
        });
      }

      if (onOpenWorkspaceDetails) {
        commands.push({
          id: 'action-open-workspace-details',
          label: 'Machine: Workspace Details',
          icon: <PanelBottomOpen size={14} />,
          category: 'Actions',
          action: onOpenWorkspaceDetails,
        });
      }
    }

    // ─── Panels ──────────────────────────────────────────
    commands.push(
      {
        id: 'panel-git',
        label: 'Chatroom: Git Panel',
        icon: <GitBranch size={14} />,
        category: 'Panels',
        action: onOpenGitPanel,
      },
      {
        id: 'panel-configuration',
        label: 'Chatroom: Settings',
        icon: <Settings size={14} />,
        category: 'Panels',
        keywords: ['settings', 'configuration', 'config', 'preferences'],
        action: () => onOpenSettings('setup'),
      },
      {
        id: 'panel-event-stream',
        label: 'Chatroom: Event Stream',
        icon: <Activity size={14} />,
        category: 'Panels',
        action: onOpenEventStream,
      },
      {
        id: 'panel-pending-review',
        label: 'Chatroom: Pending Review',
        icon: <ClipboardCheck size={14} />,
        category: 'Panels',
        action: onOpenPendingReview,
      },
      {
        id: 'panel-backlog',
        label: 'Chatroom: Backlog',
        icon: <ListTodo size={14} />,
        category: 'Panels',
        action: onOpenBacklog,
      }
    );

    // ─── View ──────────────────────────────────────────────
    if (onShowExplorer) {
      commands.push({
        id: 'view-explorer',
        label: 'View: Show Explorer',
        icon: <Files size={14} />,
        category: 'View',
        keywords: ['files', 'tree', 'explorer', 'workspace'],
        action: onShowExplorer,
      });
    }

    if (onShowMessages) {
      commands.push({
        id: 'view-messages',
        label: 'View: Show Messages',
        icon: <MessagesSquare size={14} />,
        category: 'View',
        keywords: ['chat', 'messages', 'feed', 'history'],
        action: onShowMessages,
      });
    }

    // ─── Process Manager ────────────────────────────────
    if (onOpenProcessManager) {
      commands.push({
        id: 'panel-process-manager',
        label: 'Chatroom: Process Manager',
        icon: <Terminal size={14} />,
        category: 'Panels',
        action: onOpenProcessManager,
      });
    }

    return commands;
  }, [
    onOpenSettings,
    onOpenEventStream,
    onOpenGitPanel,
    onOpenBacklog,
    onOpenPendingReview,
    onOpenChatroomSwitcher,
    onOpenFileSelector,
    onOpenInVSCode,
    onOpenInGitHubDesktop,
    onOpenPROnGitHub,
    onOpenPRReview,
    onViewGitHubPullRequests,
    onViewGitHubRepository,
    onOpenWorkspaceDetails,
    runnableCommands,
    onOpenProcessManagerWithCommand,
    onRunCommand,
    onOpenProcessManager,
    onShowExplorer,
    onShowMessages,
    favoritesVersion,
    workspaceCommands,
  ]);
}
