'use client';

import { useEffect, useMemo, useState } from 'react';
import {
  Activity,
  AlertTriangle,
  ArrowRightLeft,
  ClipboardCheck,
  Code2,
  Files,
  FileSearch,
  GitBranch,
  GitPullRequest,
  ListTodo,
  MessagesSquare,
  MessageSquare,
  PanelBottomOpen,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Settings,
  StopCircle,
  Terminal,
  Trash2,
} from 'lucide-react';
import { SiGithub } from 'react-icons/si';
import { toast } from 'sonner';

import type { SavedCommand } from '../../types/savedCommand';
import { getCommandFavoritesStore } from '../../lib/commandFavoritesStore';
import { getCommandUsageStore } from '../../lib/commandUsageStore';
import type { CommandItem, SettingsTab } from './types';

export type { SettingsTab };

export type { SavedCommand };

interface UseCommandPaletteCommandsProps {
  onOpenSettings: (tab: SettingsTab) => void;
  onOpenEventStream: () => void;
  onOpenGitPanel: () => void;
  onOpenBacklog: () => void;
  onOpenPendingReview: () => void;
  /** Navigation callbacks */
  onOpenChatroomSwitcher: () => void;
  onCreateNewChatroom?: (() => void) | null;
  onOpenFileSelector: () => void;
  /** Workspace action callbacks — conditionally available (legacy single-workspace) */
  onOpenInVSCode?: (() => void) | null;
  onOpenInGitHubDesktop?: (() => void) | null;
  onOpenPROnGitHub?: (() => void) | null;
  onOpenPRReview?: (() => void) | null;
  onViewGitHubPullRequests?: (() => void) | null;
  onViewGitHubRepository?: (() => void) | null;
  onOpenWorkspaceDetails?: (() => void) | null;
  /** Runnable commands for matching favorites to scripts */
  runnableCommands?: Array<{ name: string; script: string; source: string }>;
  /** Callback to open the Process Manager with a specific command selected */
  onOpenProcessManagerWithCommand?: (commandName: string) => void;
  /** Callback to directly execute a command (run + open terminal) */
  onRunCommand?: (commandName: string, script: string) => void;
  /** Callback to open the Process Manager */
  onOpenProcessManager?: () => void;
  /** Callback to switch to Explorer view */
  onShowExplorer?: (() => void) | null;
  /** Callback to switch to Messages view */
  onShowMessages?: () => void;
  /** Callback to toggle chat in split panel (explorer view only) */
  onToggleChatSplitPanel?: (() => void) | null;
  /** Callback to start all remote agents with their last config */
  onStartAllRemoteAgents?: (() => void) | null;
  /** Callback to stop all remote agents */
  onStopAllRemoteAgents?: (() => void) | null;
  /** Callback to restart all remote agents (starts if stopped, restarts if running) */
  onRestartAllRemoteAgents?: (() => void) | null;
  /**
   * Per-workspace command items generated by WorkspaceCommandsAggregator.
   * When provided, these replace the legacy single-workspace action commands
   * (onOpenInVSCode, onOpenInGitHubDesktop, etc.).
   */
  workspaceCommands?: CommandItem[];
  /** Callback to open the Create Command modal */
  onCreateCommand?: (() => void) | null;
  /** Saved commands to show in the command palette */
  savedCommands?: SavedCommand[];
  /** Callback to execute a saved command (send its prompt as a message) */
  onExecuteSavedCommand?: ((cmd: SavedCommand) => void) | null;
  /** Callback to edit a saved command */
  onEditSavedCommand?: ((cmd: SavedCommand) => void) | null;
  /** Callback to delete a saved command */
  onDeleteSavedCommand?: ((commandId: string, name: string) => void) | null;
  /** The commandId currently awaiting delete confirmation (if any) */
  confirmingDeleteCommandId?: string | null;
  /** Force the daemon to immediately re-push observed workspace state (git status, recent commits, PRs). */
  onRefreshWorkspaceState?: (() => void) | null;
}

/**
 * Hook that builds the list of commands for the command palette.
 *
 * Provides panel navigation commands and workspace action commands.
 * Action commands are conditionally included based on workspace availability.
 */
export function useCommandPaletteCommands({
  onOpenSettings,
  onOpenEventStream,
  onOpenGitPanel,
  onOpenBacklog,
  onOpenPendingReview,
  onOpenChatroomSwitcher,
  onCreateNewChatroom,
  onOpenFileSelector,
  onOpenInVSCode,
  onOpenInGitHubDesktop,
  onOpenPROnGitHub,
  onOpenPRReview,
  onViewGitHubPullRequests,
  onViewGitHubRepository,
  onOpenWorkspaceDetails,
  runnableCommands,
  onOpenProcessManagerWithCommand,
  onRunCommand,
  onOpenProcessManager,
  onShowExplorer,
  onShowMessages,
  onToggleChatSplitPanel,
  workspaceCommands,
  onStartAllRemoteAgents,
  onStopAllRemoteAgents,
  onRestartAllRemoteAgents,
  onCreateCommand,
  savedCommands,
  onExecuteSavedCommand,
  onEditSavedCommand,
  onDeleteSavedCommand,
  confirmingDeleteCommandId,
  onRefreshWorkspaceState,
}: UseCommandPaletteCommandsProps): CommandItem[] {
  // Track favorites changes from Process Manager via custom event
  const [favoritesVersion, setFavoritesVersion] = useState(0);
  useEffect(() => {
    const handler = () => setFavoritesVersion((v) => v + 1);
    window.addEventListener('chatroom:favorites-changed', handler);
    return () => window.removeEventListener('chatroom:favorites-changed', handler);
  }, []);

  return useMemo<CommandItem[]>(() => {
    const commands: CommandItem[] = [];

    // ─── Saved Commands (custom user prompts) ──────────────────────
    if (savedCommands && savedCommands.length > 0 && onExecuteSavedCommand) {
      for (const cmd of savedCommands) {
        commands.push({
          id: `saved-cmd-${cmd._id}`,
          label: `Command: ${cmd.name}`,
          icon: <MessageSquare size={14} />,
          category: 'Commands',
          keywords: [cmd.name],
          action: () => onExecuteSavedCommand(cmd),
          secondaryActions: [
            ...(onEditSavedCommand
              ? [
                  {
                    id: `saved-cmd-edit-${cmd._id}`,
                    label: 'Edit',
                    icon: <Pencil size={12} />,
                    action: () => onEditSavedCommand(cmd),
                  },
                ]
              : []),
            ...(onDeleteSavedCommand
              ? [
                  {
                    id: `saved-cmd-delete-${cmd._id}`,
                    label: confirmingDeleteCommandId === cmd._id ? 'Confirm?' : 'Delete',
                    icon:
                      confirmingDeleteCommandId === cmd._id ? (
                        <AlertTriangle size={12} />
                      ) : (
                        <Trash2 size={12} />
                      ),
                    action: () => onDeleteSavedCommand(cmd._id, cmd.name),
                  },
                ]
              : []),
          ],
        });
      }
    }

    // ─── Favorites (favourited commands from process manager) ────────
    if (runnableCommands) {
      const favoritesStore = getCommandFavoritesStore();
      const favorites = favoritesStore.getAll();

      for (const cmd of runnableCommands) {
        if (favorites.has(cmd.name)) {
          commands.push({
            id: `fav-${cmd.name}`,
            label: cmd.name,
            icon: <Terminal size={14} />,
            category: 'Commands',
            // showOutputInline: true causes CommandPalette to call inlineCommand.run()
            showOutputInline: true,
            script: cmd.script,
            // action is a fallback for non-inline environments
            action: () => {
              if (onRunCommand) {
                onRunCommand(cmd.name, cmd.script);
              } else if (onOpenProcessManagerWithCommand) {
                onOpenProcessManagerWithCommand(cmd.name);
              }
            },
          });
        }
      }
    }

    // ─── Navigate (shown first) ──────────────────────────
    commands.push({
      id: 'nav-switch-chatroom',
      label: 'Chatroom: Switch Chatroom',
      icon: <ArrowRightLeft size={14} />,
      category: 'Navigate',
      shortcut: '⌘K',
      action: onOpenChatroomSwitcher,
    });

    if (onCreateNewChatroom) {
      commands.push({
        id: 'nav-new-chatroom',
        label: 'Chatroom: New Chatroom',
        icon: <Plus size={14} />,
        category: 'Navigate',
        keywords: ['new', 'create', 'chatroom'],
        action: onCreateNewChatroom,
      });
    }

    // ─── Create Command action ────────────────────────────────────
    if (onCreateCommand) {
      commands.push({
        id: 'action-create-command',
        label: 'Create Command',
        icon: <Plus size={14} />,
        category: 'Actions',
        keywords: ['new', 'create', 'command', 'prompt', 'saved'],
        action: onCreateCommand,
      });
    }

    commands.push({
      id: 'nav-go-to-file',
      label: 'Chatroom: Go to File',
      icon: <FileSearch size={14} />,
      category: 'Navigate',
      shortcut: '⌘P',
      action: onOpenFileSelector,
    });

    // ─── Workspace Actions ────────────────────────────────
    // When workspaceCommands is provided (multi-workspace mode), use those.
    // Otherwise fall back to legacy single-workspace callbacks.
    if (workspaceCommands && workspaceCommands.length > 0) {
      commands.push(...workspaceCommands);
    } else {
      // Legacy single-workspace commands (backward compatible)
      if (onOpenInVSCode) {
        commands.push({
          id: 'action-open-vscode',
          label: 'Machine: Open in VS Code',
          icon: <Code2 size={14} />,
          category: 'Actions',
          action: onOpenInVSCode,
        });
      }

      if (onOpenInGitHubDesktop) {
        commands.push({
          id: 'action-open-github-desktop',
          label: 'Machine: Open in GitHub Desktop',
          icon: <SiGithub size={14} />,
          category: 'Actions',
          action: onOpenInGitHubDesktop,
        });
      }

      if (onViewGitHubPullRequests) {
        commands.push({
          id: 'action-view-github-prs',
          label: 'Github: View My Pull Requests',
          icon: <SiGithub size={14} />,
          category: 'Actions',
          keywords: ['PR', 'PRs'],
          action: onViewGitHubPullRequests,
        });
      }

      if (onViewGitHubRepository) {
        commands.push({
          id: 'action-view-github-repo',
          label: 'Github: View Repository',
          icon: <SiGithub size={14} />,
          category: 'Actions',
          keywords: ['repo', 'repository', 'github'],
          action: onViewGitHubRepository,
        });
      }

      if (onOpenPROnGitHub) {
        commands.push({
          id: 'action-open-pr-github',
          label: 'Github: View Current Pull Request',
          icon: <GitPullRequest size={14} />,
          category: 'Actions',
          keywords: ['PR', 'pull request', 'Github PR'],
          action: onOpenPROnGitHub,
        });
      }

      if (onOpenPRReview) {
        commands.push({
          id: 'action-pr-review-diff',
          label: 'Chatroom: Review Pull Requests',
          icon: <GitPullRequest size={14} />,
          category: 'Actions',
          keywords: ['PR', 'PRs', 'Review'],
          action: onOpenPRReview,
        });
      }

      if (onOpenWorkspaceDetails) {
        commands.push({
          id: 'action-open-workspace-details',
          label: 'Machine: Workspace Details',
          icon: <PanelBottomOpen size={14} />,
          category: 'Actions',
          action: onOpenWorkspaceDetails,
        });
      }

      // Git Diff has no global registration here.
      //
      // Per-workspace 'Git: Show Current Changes' commands are contributed by
      // `useWorkspaceCommandItems` (one per workspace). When zero workspaces are
      // registered there's nothing meaningful to diff, so users open the Git
      // Panel via `panel-git` below and pick a workspace from there.

      // ─── Preferences ─────────────────────────────────────────────
      commands.push({
        id: 'action-reset-command-stats',
        label: 'Preferences: Reset Command Stats',
        icon: <Settings size={14} />,
        category: 'Preferences',
        keywords: ['reset', 'clear', 'stats', 'usage', 'frecency'],
        action: () => {
          getCommandUsageStore().clear();
          toast.success('Command stats cleared');
        },
      });
    }

    // ─── Panels ──────────────────────────────────────────
    commands.push(
      {
        id: 'panel-git',
        label: 'Chatroom: Git Panel',
        icon: <GitBranch size={14} />,
        category: 'Panels',
        action: onOpenGitPanel,
      },
      {
        id: 'panel-configuration',
        label: 'Chatroom: Settings',
        icon: <Settings size={14} />,
        category: 'Panels',
        keywords: ['settings', 'configuration', 'config', 'preferences'],
        action: () => onOpenSettings('setup'),
      },
      {
        id: 'panel-event-stream',
        label: 'Chatroom: Event Stream',
        icon: <Activity size={14} />,
        category: 'Panels',
        action: onOpenEventStream,
      },
      {
        id: 'panel-pending-review',
        label: 'Chatroom: Pending Review',
        icon: <ClipboardCheck size={14} />,
        category: 'Panels',
        action: onOpenPendingReview,
      },
      {
        id: 'panel-backlog',
        label: 'Chatroom: Backlog',
        icon: <ListTodo size={14} />,
        category: 'Panels',
        action: onOpenBacklog,
      }
    );

    // ─── View ──────────────────────────────────────────────
    if (onShowExplorer) {
      commands.push({
        id: 'view-explorer',
        label: 'View: Show Explorer',
        icon: <Files size={14} />,
        category: 'View',
        keywords: ['files', 'tree', 'explorer', 'workspace'],
        action: onShowExplorer,
      });
    }

    if (onShowMessages) {
      commands.push({
        id: 'view-messages',
        label: 'View: Show Messages',
        icon: <MessagesSquare size={14} />,
        category: 'View',
        keywords: ['chat', 'messages', 'feed', 'history'],
        action: onShowMessages,
      });
    }

    if (onToggleChatSplitPanel) {
      commands.push({
        id: 'view-toggle-chat-split-panel',
        label: 'View: Toggle Split Chat',
        icon: <MessageSquare size={14} />,
        category: 'View',
        keywords: ['chat', 'split', 'panel', 'messages', 'side', 'toggle'],
        action: onToggleChatSplitPanel,
      });
    }

    // ─── Agents ──────────────────────────────────────────────
    if (onStartAllRemoteAgents) {
      commands.push({
        id: 'agents-start-all-remote',
        label: 'Chatroom: Start all remote agents',
        icon: <Play size={14} />,
        category: 'Agents',
        keywords: ['start', 'remote', 'run', 'launch', 'all'],
        action: onStartAllRemoteAgents,
      });
    }

    if (onStopAllRemoteAgents) {
      commands.push({
        id: 'agents-stop-all-remote',
        label: 'Chatroom: Stop all remote agents',
        icon: <StopCircle size={14} />,
        category: 'Agents',
        keywords: ['stop', 'remote', 'kill', 'terminate', 'all'],
        action: onStopAllRemoteAgents,
      });
    }

    if (onRestartAllRemoteAgents) {
      commands.push({
        id: 'agents-restart-all-remote',
        label: 'Chatroom: Restart all remote agents',
        icon: <RefreshCw size={14} />,
        category: 'Agents',
        keywords: ['restart', 'remote', 'reload', 'refresh', 'all'],
        action: onRestartAllRemoteAgents,
      });
    }

    // ─── Workspace ──────────────────────────────────────────────
    if (onRefreshWorkspaceState) {
      commands.push({
        id: 'workspace.refreshState',
        label: 'Chatroom: Refresh Workspace State',
        icon: <RefreshCw size={14} />,
        category: 'Actions',
        // Omit "pull" / "git pull" — this command re-pushes observed state from the daemon, not VCS pull.
        keywords: ['refresh', 'reload', 'sync', 'workspace', 'state', 'update', 'git', 'observed', 'daemon'],
        action: onRefreshWorkspaceState,
      });
    }

    // ─── Process Manager ────────────────────────────────
    if (onOpenProcessManager) {
      commands.push({
        id: 'panel-process-manager',
        label: 'Chatroom: Process Manager',
        icon: <Terminal size={14} />,
        category: 'Panels',
        action: onOpenProcessManager,
      });
    }

    return commands;
  }, [
    onOpenSettings,
    onOpenEventStream,
    onOpenGitPanel,
    onOpenBacklog,
    onOpenPendingReview,
    onOpenChatroomSwitcher,
    onCreateNewChatroom,
    onOpenFileSelector,
    onOpenInVSCode,
    onOpenInGitHubDesktop,
    onOpenPROnGitHub,
    onOpenPRReview,
    onViewGitHubPullRequests,
    onViewGitHubRepository,
    onOpenWorkspaceDetails,
    runnableCommands,
    onOpenProcessManagerWithCommand,
    onRunCommand,
    onOpenProcessManager,
    onShowExplorer,
    onShowMessages,
    onToggleChatSplitPanel,
    favoritesVersion,
    workspaceCommands,
    onStartAllRemoteAgents,
    onStopAllRemoteAgents,
    onRestartAllRemoteAgents,
    onCreateCommand,
    savedCommands,
    onExecuteSavedCommand,
    onEditSavedCommand,
    onDeleteSavedCommand,
    confirmingDeleteCommandId,
    onRefreshWorkspaceState,
  ]);
}
