/**
 * Classify Reminders Integration Tests
 *
 * Tests the complete reminder messages generated by the classify command,
 * including classification-specific guidance for new_feature, question, and follow_up.
 */

import type { SessionId } from 'convex-helpers/server/sessions';
import { describe, expect, test } from 'vitest';

import { api } from '../../../convex/_generated/api';
import type { Id } from '../../../convex/_generated/dataModel';
import { t } from '../../../test.setup';

/**
 * Helper to create a test session and authenticate
 */
async function createTestSession(sessionId: string): Promise<{ sessionId: SessionId }> {
  const login = await t.mutation(api.auth.loginAnon, {
    sessionId: sessionId as SessionId,
  });
  expect(login.success).toBe(true);
  return { sessionId: sessionId as SessionId };
}

/**
 * Helper to create a Pair team chatroom
 */
async function createPairTeamChatroom(sessionId: SessionId): Promise<Id<'chatroom_rooms'>> {
  const chatroomId = await t.mutation(api.chatrooms.create, {
    sessionId,
    teamId: 'pair',
    teamName: 'Pair Team',
    teamRoles: ['builder', 'reviewer'],
    teamEntryPoint: 'builder',
  });
  return chatroomId;
}

/**
 * Helper to join participants to the chatroom
 */
async function joinParticipants(
  sessionId: SessionId,
  chatroomId: Id<'chatroom_rooms'>,
  roles: string[]
): Promise<void> {
  for (const role of roles) {
    await t.mutation(api.participants.join, {
      sessionId,
      chatroomId,
      role,
    });
  }
}

describe('Classify Reminders', () => {
  test('materializes complete classify reminder for new_feature classification', async () => {
    // ===== SETUP =====
    const { sessionId } = await createTestSession('test-classify-new-feature');
    const chatroomId = await createPairTeamChatroom(sessionId);
    await joinParticipants(sessionId, chatroomId, ['builder', 'reviewer']);

    // User sends message
    await t.mutation(api.messages.sendMessage, {
      sessionId,
      chatroomId,
      senderRole: 'user',
      content: 'Add dark mode toggle to the application',
      type: 'message',
    });

    // Builder claims and starts the task
    await t.mutation(api.tasks.claimTask, {
      sessionId,
      chatroomId,
      role: 'builder',
    });

    const startResult = await t.mutation(api.tasks.startTask, {
      sessionId,
      chatroomId,
      role: 'builder',
    });

    // Classify as new_feature
    const result = await t.mutation(api.messages.taskStarted, {
      sessionId,
      chatroomId,
      role: 'builder',
      taskId: startResult.taskId,
      originMessageClassification: 'new_feature',
      rawStdin: `---TITLE---
Dark Mode Toggle
---DESCRIPTION---
Add a toggle in settings for dark/light mode
---TECH_SPECS---
Use React Context + CSS variables`,
      convexUrl: 'http://127.0.0.1:3210',
    });

    // Materialize the complete CLI output for classify command
    const classification = 'new_feature';

    const fullCliOutput = `✅ Task acknowledged and classified
   Classification: ${classification}
   Task: Add dark mode toggle to the application

💡 ${result.reminder}`;

    // Verify the complete reminder structure matches expected format
    // The inline snapshot will materialize the full message for human review in the test file
    expect(fullCliOutput).toMatchInlineSnapshot(`
      "✅ Task acknowledged and classified
         Classification: new_feature
         Task: Add dark mode toggle to the application

      💡 ✅ Task acknowledged as NEW FEATURE.

      **Next steps:**
      1. Implement the feature
      2. Send \`report-progress\` at milestones (e.g., after major changes, when blocked)
      3. Commit your changes
      4. MUST hand off to reviewer for approval:

      \`\`\`bash
      CHATROOM_CONVEX_URL=http://127.0.0.1:3210 chatroom handoff --chatroom-id="10002;chatroom_rooms" --role="builder" --next-role="reviewer" << 'EOF'
      ---MESSAGE---
      [Your message here]
      EOF
      \`\`\`

      💡 You're working on:
      Task ID: 10006;chatroom_tasks"
    `);

    // Verify reminder structure
    expect(result.success).toBe(true);
    expect(result.classification).toBe('new_feature');
    expect(result.reminder).toBeDefined();
    expect(result.reminder).toContain('NEW FEATURE');
    expect(result.reminder).toContain('hand off to reviewer');
  });

  test('materializes complete classify reminder for question classification', async () => {
    // ===== SETUP =====
    const { sessionId } = await createTestSession('test-classify-question');
    const chatroomId = await createPairTeamChatroom(sessionId);
    await joinParticipants(sessionId, chatroomId, ['builder', 'reviewer']);

    // User sends message
    await t.mutation(api.messages.sendMessage, {
      sessionId,
      chatroomId,
      senderRole: 'user',
      content: 'How does the authentication system work?',
      type: 'message',
    });

    // Builder claims and starts the task
    await t.mutation(api.tasks.claimTask, {
      sessionId,
      chatroomId,
      role: 'builder',
    });

    const startResult = await t.mutation(api.tasks.startTask, {
      sessionId,
      chatroomId,
      role: 'builder',
    });

    // Classify as question
    const result = await t.mutation(api.messages.taskStarted, {
      sessionId,
      chatroomId,
      role: 'builder',
      taskId: startResult.taskId,
      originMessageClassification: 'question',
      convexUrl: 'http://127.0.0.1:3210',
    });

    // Materialize the complete CLI output for classify command
    const classification = 'question';

    const fullCliOutput = `✅ Task acknowledged and classified
   Classification: ${classification}
   Task: How does the authentication system work?

💡 ${result.reminder}`;

    // Verify the complete reminder structure matches expected format
    expect(fullCliOutput).toMatchInlineSnapshot(`
      "✅ Task acknowledged and classified
         Classification: question
         Task: How does the authentication system work?

      💡 ✅ Task acknowledged as QUESTION.

      **Next steps:**
      1. Send a progress update: \`CHATROOM_CONVEX_URL=http://127.0.0.1:3210 chatroom report-progress --chatroom-id="10013;chatroom_rooms" --role="builder" << 'EOF'
      ---MESSAGE---
      [Your progress message here]
      EOF\`
      2. Answer the user's question
      3. When done, hand off directly to user:

      \`\`\`bash
      CHATROOM_CONVEX_URL=http://127.0.0.1:3210 chatroom handoff --chatroom-id="10013;chatroom_rooms" --role="builder" --next-role="user" << 'EOF'
      ---MESSAGE---
      [Your message here]
      EOF
      \`\`\`

      💡 You're working on:
      Task ID: 10017;chatroom_tasks"
    `);

    // Verify reminder structure
    expect(result.success).toBe(true);
    expect(result.classification).toBe('question');
    expect(result.reminder).toBeDefined();
    expect(result.reminder).toContain('QUESTION');
    expect(result.reminder).toContain('hand off directly to user');
  });

  test('materializes complete classify reminder for follow_up classification', async () => {
    // ===== SETUP =====
    const { sessionId } = await createTestSession('test-classify-follow-up');
    const chatroomId = await createPairTeamChatroom(sessionId);
    await joinParticipants(sessionId, chatroomId, ['builder', 'reviewer']);

    // User sends follow-up message
    await t.mutation(api.messages.sendMessage, {
      sessionId,
      chatroomId,
      senderRole: 'user',
      content: 'Can you also add filtering?',
      type: 'message',
    });

    // Builder claims and starts the task
    await t.mutation(api.tasks.claimTask, {
      sessionId,
      chatroomId,
      role: 'builder',
    });

    const startResult = await t.mutation(api.tasks.startTask, {
      sessionId,
      chatroomId,
      role: 'builder',
    });

    // Classify as follow_up
    const result = await t.mutation(api.messages.taskStarted, {
      sessionId,
      chatroomId,
      role: 'builder',
      taskId: startResult.taskId,
      originMessageClassification: 'follow_up',
      convexUrl: 'http://127.0.0.1:3210',
    });

    // Materialize the complete CLI output for classify command
    const classification = 'follow_up';

    const fullCliOutput = `✅ Task acknowledged and classified
   Classification: ${classification}
   Task: Can you also add filtering?

💡 ${result.reminder}`;

    // Verify the complete reminder structure matches expected format
    expect(fullCliOutput).toMatchInlineSnapshot(`
      "✅ Task acknowledged and classified
         Classification: follow_up
         Task: Can you also add filtering?

      💡 ✅ Task acknowledged as FOLLOW UP.

      **Next steps:**
      1. Complete the follow-up work
      2. Send \`report-progress\` at milestones for visibility
      3. Follow-up inherits the workflow rules from the original task:
         - If original was a QUESTION → hand off to user when done
         - If original was a NEW FEATURE → hand off to reviewer when done

      💡 You're working on:
      Task ID: 10028;chatroom_tasks"
    `);

    // Verify reminder structure
    expect(result.success).toBe(true);
    expect(result.classification).toBe('follow_up');
    expect(result.reminder).toBeDefined();
    expect(result.reminder).toContain('FOLLOW UP');
    expect(result.reminder).toContain('inherits the workflow rules');
  });
});
