/**
 * Convex API types for CLI
 *
 * This file is auto-generated by scripts/sync-cli-api.ts
 * Do not edit directly - run 'pnpm --filter chatroom-cli sync' to regenerate.
 *
 * @module
 */

// Re-export the generated API
export { api } from './api.js';

// Type for Convex IDs - matches the Convex GenericId type
export type Id<TableName extends string> = string & { __tableName: TableName };

// Re-export common types used by the CLI
export interface Chatroom {
  _id: Id<'chatroom_rooms'>;
  status: 'active' | 'interrupted' | 'completed';
  ownerId: Id<'users'>;
  teamId?: string;
  teamName?: string;
  teamRoles?: string[];
  teamEntryPoint?: string;
  _creationTime?: number;
}

export interface Message {
  _id: Id<'chatroom_messages'>;
  chatroomId: Id<'chatroom_rooms'>;
  senderRole: string;
  content: string;
  type: 'message' | 'handoff' | 'interrupt' | 'join';
  targetRole?: string;
  claimedByRole?: string;
  classification?: 'question' | 'new_feature' | 'follow_up';
  taskOriginMessageId?: Id<'chatroom_messages'>;
  taskId?: Id<'chatroom_tasks'>;
  attachedTaskIds?: Id<'chatroom_tasks'>[];
  _creationTime?: number;
}

export interface Task {
  _id: Id<'chatroom_tasks'>;
  chatroomId: Id<'chatroom_rooms'>;
  createdBy: string;
  content: string;
  status: 'pending' | 'in_progress' | 'queued' | 'backlog' | 'completed' | 'cancelled';
  assignedTo?: string;
  sourceMessageId?: Id<'chatroom_messages'>;
  createdAt: number;
  updatedAt: number;
  startedAt?: number;
  completedAt?: number;
  queuePosition: number;
}

export interface TaskWithMessage {
  task: Task;
  message: Message | null;
}

export interface AllowedHandoffRoles {
  availableRoles: string[];
  canHandoffToUser: boolean;
  restrictionReason: string | null;
  currentClassification: 'question' | 'new_feature' | 'follow_up' | null;
}

export interface ContextWindow {
  originMessage: Message | null;
  contextMessages: Message[];
  classification: 'question' | 'new_feature' | 'follow_up' | null;
}

export interface RolePromptResponse {
  prompt: string;
  currentClassification: 'question' | 'new_feature' | 'follow_up' | null;
  availableHandoffRoles: string[];
  canHandoffToUser: boolean;
  restrictionReason: string | null;
}

export interface Participant {
  _id: Id<'chatroom_participants'>;
  chatroomId: Id<'chatroom_rooms'>;
  role: string;
  status: 'active' | 'waiting' | 'idle';
  _creationTime?: number;
}

export interface TeamReadinessInfo {
  isReady: boolean;
  teamName: string;
  expectedRoles: string[];
  presentRoles: string[];
  missingRoles: string[];
}

// CLI Auth response types
export interface AuthRequestResult {
  requestId: string;
  expiresAt: number;
}

export interface AuthRequestStatus {
  status: 'pending' | 'approved' | 'denied' | 'expired' | 'not_found';
  sessionId?: string;
  expiresAt?: number;
}

export interface SessionValidation {
  valid: boolean;
  userId?: string;
  userName?: string;
  reason?: string;
}
