/**
 * ROLE GUIDANCE section - shows role-specific workflow guidance.
 */

import type { PromptSection, TaskDeliveryContext } from '../types';

export const roleGuidanceSection: PromptSection = {
  id: 'role-guidance',
  title: 'ROLE GUIDANCE',
  icon: '📋',

  shouldRender: () => true,

  render: (ctx: TaskDeliveryContext): string => {
    // The role prompt is already generated by getRolePrompt
    // We just include it directly
    return ctx.rolePrompt.prompt;
  },
};
