import { SKETCH_CANVAS_COLORS } from './sketchConstants'; import { normalizeRect, toBackingRect } from './sketchCanvasCoords'; import type { SketchRect } from './sketchSelectionTypes';
export function scaleImageData(source:ImageData,w:number,h:number){const src=document.createElement('canvas');src.width=source.width;src.height=source.height;src.getContext('2d')!.putImageData(source,0,0);const dst=document.createElement('canvas');dst.width=Math.max(1,Math.round(w));dst.height=Math.max(1,Math.round(h));const c=dst.getContext('2d')!;c.imageSmoothingEnabled=false;c.drawImage(src,0,0,dst.width,dst.height);return c.getImageData(0,0,dst.width,dst.height);}
export async function imageDataToPngBlob(data:ImageData){const c=document.createElement('canvas');c.width=data.width;c.height=data.height;c.getContext('2d')!.putImageData(data,0,0);return new Promise<Blob|null>(r=>c.toBlob(r,'image/png'));}
export async function imageBlobToImageData(blob: Blob): Promise<ImageData> { const url = URL.createObjectURL(blob); try { const img = await new Promise<HTMLImageElement>((resolve, reject) => { const el = new Image(); el.onload = () => resolve(el); el.onerror = () => reject(new Error('image load failed')); el.src = url; }); const c = document.createElement('canvas'); c.width = img.naturalWidth; c.height = img.naturalHeight; const ctx = c.getContext('2d'); if (!ctx) throw new Error('no 2d context'); ctx.drawImage(img, 0, 0); return ctx.getImageData(0, 0, c.width, c.height); } finally { URL.revokeObjectURL(url); } }
export function fitImageDataToBounds(data: ImageData, maxWidth: number, maxHeight: number): { imageData: ImageData; width: number; height: number } { const scale = Math.min(1, maxWidth / data.width, maxHeight / data.height); const width = Math.max(1, Math.round(data.width * scale)); const height = Math.max(1, Math.round(data.height * scale)); return { imageData: scale === 1 ? data : scaleImageData(data, width, height), width, height }; }
export function fillRectWithBackground(ctx:CanvasRenderingContext2D,r:SketchRect,background=SKETCH_CANVAS_COLORS.background){ctx.fillStyle=background;ctx.fillRect(r.x,r.y,r.width,r.height);}
export function drawImageDataAt(ctx:CanvasRenderingContext2D,data:ImageData,r:SketchRect){const c=document.createElement('canvas');c.width=data.width;c.height=data.height;c.getContext('2d')!.putImageData(data,0,0);ctx.drawImage(c,r.x,r.y,r.width,r.height);}
export function liftPixels(ctx:CanvasRenderingContext2D,_canvas:HTMLCanvasElement,r:SketchRect,dpr:number){const b=toBackingRect(r,dpr);if(b.width<1||b.height<1)return null;const data=ctx.getImageData(b.x,b.y,b.width,b.height);fillRectWithBackground(ctx,r);return data;}
export function resizeBoundsFromHandle(handle: import('./sketchSelectionTypes').ResizeHandle,start:SketchRect,pointer:{x:number;y:number}):SketchRect{const ax=handle.includes('w')?start.x+start.width:start.x;const ay=handle.includes('n')?start.y+start.height:start.y;const r=normalizeRect(ax,ay,pointer.x,pointer.y);return {...r,width:Math.max(4,r.width),height:Math.max(4,r.height)};}
