'use client';
import { useCallback, useRef, useState } from 'react';
import { canvasPointFromEvent, normalizeRect, pointInRect } from './sketchCanvasCoords';
import { drawImageDataAt, imageDataToPngBlob, liftPixels, scaleImageData } from './sketchSelectionUtils';
import { SKETCH_MIN_SELECTION_CSS_PX, type ResizeHandle, type SketchFloatingSelection, type SketchRect } from './sketchSelectionTypes';
type Mode = 'idle' | 'creating' | 'moving' | 'resizing';
export function useSketchSelection({ getCtx, getCanvas, getDpr: _getDpr, updateHasContent, getHasContent: _getHasContent }: { getCtx: () => CanvasRenderingContext2D | null; getCanvas: () => HTMLCanvasElement | null; getDpr: () => number; updateHasContent: (v: boolean) => void; getHasContent: () => boolean }) {
  const [marquee, setMarquee] = useState<SketchRect | null>(null); const [selection, setSelection] = useState<SketchFloatingSelection | null>(null);
  const marqueeRef = useRef<SketchRect | null>(null); const selectionRef = useRef<SketchFloatingSelection | null>(null); const baseRef = useRef<ImageData | null>(null); const mode = useRef<Mode>('idle'); const start = useRef({ x: 0, y: 0 }); const drag = useRef({ x: 0, y: 0 }); const resize = useRef<{ handle: ResizeHandle; bounds: SketchRect; data: ImageData } | null>(null);
  const setSel = (v: SketchFloatingSelection | null) => { selectionRef.current = v; setSelection(v); };
  const redraw = useCallback(() => { const c = getCtx(), s = selectionRef.current, b = baseRef.current; if (c && s && b) { c.putImageData(b, 0, 0); drawImageDataAt(c, s.imageData, s.bounds); } }, [getCtx]);
  const commitSelection = useCallback(() => { const c = getCtx(), s = selectionRef.current; if (c && s) drawImageDataAt(c, s.imageData, s.bounds); baseRef.current = null; setSel(null); marqueeRef.current = null; setMarquee(null); if (s) updateHasContent(true); }, [getCtx, updateHasContent]);
  const deleteSelection = useCallback(() => { const c = getCtx(), b = baseRef.current; if (c && b) c.putImageData(b, 0, 0); baseRef.current = null; setSel(null); marqueeRef.current = null; setMarquee(null); }, [getCtx]);
  const bindSelectionPointerHandlers = useCallback((canvas: HTMLCanvasElement, dpr: number) => {
    const down = (e: PointerEvent) => { const p = canvasPointFromEvent(canvas, e, dpr); const s = selectionRef.current; if (s && pointInRect(p.x, p.y, s.bounds)) { mode.current = 'moving'; start.current = p; drag.current = { x: s.bounds.x, y: s.bounds.y }; } else { if (s) commitSelection(); mode.current = 'creating'; start.current = p; } canvas.setPointerCapture(e.pointerId); };
    const move = (e: PointerEvent) => { const p = canvasPointFromEvent(canvas, e, dpr); if (mode.current === 'creating') { const r = normalizeRect(start.current.x, start.current.y, p.x, p.y); marqueeRef.current = r; setMarquee(r); } else if (mode.current === 'moving' && selectionRef.current) { const s = selectionRef.current; setSel({ ...s, bounds: { ...s.bounds, x: drag.current.x + p.x - start.current.x, y: drag.current.y + p.y - start.current.y } }); redraw(); } };
    const up = (e: PointerEvent) => { if (mode.current === 'creating') { const r = marqueeRef.current; const c = getCtx(), target = getCanvas(); if (r && r.width >= SKETCH_MIN_SELECTION_CSS_PX && r.height >= SKETCH_MIN_SELECTION_CSS_PX && c && target) { const data = liftPixels(c, target, r, dpr); if (data) { baseRef.current = c.getImageData(0, 0, target.width, target.height); setSel({ imageData: data, bounds: r }); } } else { marqueeRef.current = null; setMarquee(null); } } else if (mode.current === 'moving') commitSelection(); mode.current = 'idle'; if (canvas.hasPointerCapture(e.pointerId)) canvas.releasePointerCapture(e.pointerId); };
    canvas.addEventListener('pointerdown', down); canvas.addEventListener('pointermove', move); canvas.addEventListener('pointerup', up); canvas.addEventListener('pointercancel', up); return () => { canvas.removeEventListener('pointerdown', down); canvas.removeEventListener('pointermove', move); canvas.removeEventListener('pointerup', up); canvas.removeEventListener('pointercancel', up); };
  }, [commitSelection, getCanvas, getCtx, redraw]);
  const onResizeHandlePointerDown = useCallback((handle: ResizeHandle, clientX: number, clientY: number) => { const s = selectionRef.current; if (!s) return; mode.current = 'resizing'; resize.current = { handle, bounds: s.bounds, data: s.imageData }; const move = (e: PointerEvent) => { const r = resize.current; if (!r) return; const dx = e.clientX - clientX, dy = e.clientY - clientY; const w = Math.max(SKETCH_MIN_SELECTION_CSS_PX, r.bounds.width + (handle.includes('e') ? dx : handle.includes('w') ? -dx : 0)); const h = Math.max(SKETCH_MIN_SELECTION_CSS_PX, r.bounds.height + (handle.includes('s') ? dy : handle.includes('n') ? -dy : 0)); setSel({ imageData: scaleImageData(r.data, w, h), bounds: { ...r.bounds, width: w, height: h } }); redraw(); }; const up = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); commitSelection(); mode.current = 'idle'; }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up); }, [commitSelection, redraw]);
  const copySelection = useCallback(async () => { const s = selectionRef.current; if (!s) return; const blob = await imageDataToPngBlob(s.imageData); if (!blob) throw new Error('copy failed'); await navigator.clipboard.write([new ClipboardItem({ 'image/png': blob })]); }, []);
  return { marquee, selection, activeHandle: null, bindSelectionPointerHandlers, onResizeHandlePointerDown, commitSelection, deleteSelection, copySelection, clearSelection: deleteSelection, hasActiveSelection: () => selectionRef.current !== null };
}
