/**
 * Convex API re-exports for CLI
 *
 * This file re-exports from the synced Convex API types.
 * The convex-api folder is generated by running 'pnpm --filter chatroom-cli sync'
 * which copies the generated types from the backend.
 *
 * @module
 */

// Re-export everything from the synced convex-api
export {
  api,
  type Id,
  type Chatroom,
  type Message,
  type Task,
  type TaskWithMessage,
  type Artifact,
  type AllowedHandoffRoles,
  type ContextWindow,
  type RolePromptResponse,
  type Participant,
  type TeamReadinessInfo,
  type AuthRequestResult,
  type AuthRequestStatus,
  type SessionValidation,
} from './convex-api/index.js';
