#!/usr/bin/env bun
/**
 * Sync Convex generated API to CLI package
 *
 * This script copies the generated Convex API files from the backend to the CLI package.
 * This allows the CLI to use the same typed API as the webapp without manual sync.
 *
 * Run this script:
 * - After running `npx convex dev` or `npx convex deploy`
 * - Before building the CLI package
 * - In CI as part of the build process
 *
 * Usage: bun scripts/sync-cli-api.ts
 */

import fs from 'fs';
import path from 'path';

const ROOT_DIR = path.resolve(import.meta.dir, '..');
const SOURCE_DIR = path.join(ROOT_DIR, 'services/backend/convex/_generated');
const TARGET_SRC_DIR = path.join(ROOT_DIR, 'packages/cli/src/convex-api');
const TARGET_DIST_DIR = path.join(ROOT_DIR, 'packages/cli/dist/convex-api');

/**
 * Files to copy from the generated folder
 */
const FILES_TO_COPY = ['api.js', 'api.d.ts'];

/**
 * Ensure target directory exists
 */
function ensureDir(dir: string): void {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`📁 Created directory: ${dir}`);
  }
}

/**
 * Copy a file with logging
 */
function copyFile(src: string, dest: string): void {
  if (!fs.existsSync(src)) {
    console.error(`❌ Source file not found: ${src}`);
    console.error(`   Run 'npx convex dev' or 'npx convex deploy' first to generate API files.`);
    process.exit(1);
  }

  fs.copyFileSync(src, dest);
  console.log(`✅ Copied: ${path.basename(src)} → ${path.relative(ROOT_DIR, dest)}`);
}

/**
 * Generate the index.ts that re-exports from api and adds custom types
 */
function generateIndex(): void {
  const indexContent = `/**
 * Convex API types for CLI
 *
 * This file is auto-generated by scripts/sync-cli-api.ts
 * Do not edit directly - run 'pnpm --filter chatroom-cli sync' to regenerate.
 *
 * @module
 */

// Re-export the generated API
export { api } from './api.js';

// Type for Convex IDs - matches the Convex GenericId type
export type Id<TableName extends string> = string & { __tableName: TableName };

// Re-export common types used by the CLI
export interface Chatroom {
  _id: Id<'chatroom_rooms'>;
  status: 'active' | 'interrupted' | 'completed';
  ownerId: Id<'users'>;
  teamId?: string;
  teamName?: string;
  teamRoles?: string[];
  teamEntryPoint?: string;
  _creationTime?: number;
}

export interface Message {
  _id: Id<'chatroom_messages'>;
  chatroomId: Id<'chatroom_rooms'>;
  senderRole: string;
  content: string;
  type: 'message' | 'handoff' | 'interrupt' | 'join';
  targetRole?: string;
  claimedByRole?: string;
  classification?: 'question' | 'new_feature' | 'follow_up';
  taskOriginMessageId?: Id<'chatroom_messages'>;
  taskId?: Id<'chatroom_tasks'>;
  _creationTime?: number;
}

export interface Task {
  _id: Id<'chatroom_tasks'>;
  chatroomId: Id<'chatroom_rooms'>;
  createdBy: string;
  content: string;
  status: 'pending' | 'in_progress' | 'queued' | 'backlog' | 'completed' | 'cancelled';
  assignedTo?: string;
  sourceMessageId?: Id<'chatroom_messages'>;
  createdAt: number;
  updatedAt: number;
  startedAt?: number;
  completedAt?: number;
  queuePosition: number;
}

export interface TaskWithMessage {
  task: Task;
  message: Message | null;
}

export interface AllowedHandoffRoles {
  availableRoles: string[];
  canHandoffToUser: boolean;
  restrictionReason: string | null;
  currentClassification: 'question' | 'new_feature' | 'follow_up' | null;
}

export interface ContextWindow {
  originMessage: Message | null;
  contextMessages: Message[];
  classification: 'question' | 'new_feature' | 'follow_up' | null;
}

export interface RolePromptResponse {
  prompt: string;
  currentClassification: 'question' | 'new_feature' | 'follow_up' | null;
  availableHandoffRoles: string[];
  canHandoffToUser: boolean;
  restrictionReason: string | null;
}

export interface Participant {
  _id: Id<'chatroom_participants'>;
  chatroomId: Id<'chatroom_rooms'>;
  role: string;
  status: 'active' | 'waiting' | 'idle';
  _creationTime?: number;
}

export interface TeamReadinessInfo {
  isReady: boolean;
  teamName: string;
  expectedRoles: string[];
  presentRoles: string[];
  missingRoles: string[];
}

// CLI Auth response types
export interface AuthRequestResult {
  requestId: string;
  expiresAt: number;
}

export interface AuthRequestStatus {
  status: 'pending' | 'approved' | 'denied' | 'expired' | 'not_found';
  sessionId?: string;
  expiresAt?: number;
}

export interface SessionValidation {
  valid: boolean;
  userId?: string;
  userName?: string;
  reason?: string;
}
`;

  const indexPath = path.join(TARGET_SRC_DIR, 'index.ts');
  fs.writeFileSync(indexPath, indexContent);
  console.log(`✅ Generated: packages/cli/src/convex-api/index.ts`);
}

/**
 * Main sync function
 */
function sync(): void {
  console.log('');
  console.log('🔄 Syncing Convex API to CLI...');
  console.log(`   Source: ${path.relative(ROOT_DIR, SOURCE_DIR)}`);
  console.log(`   Target: ${path.relative(ROOT_DIR, TARGET_SRC_DIR)}`);
  console.log('');

  // Ensure source directory exists
  if (!fs.existsSync(SOURCE_DIR)) {
    console.error(`❌ Source directory not found: ${SOURCE_DIR}`);
    console.error(`   Run 'npx convex dev' or 'npx convex deploy' first.`);
    process.exit(1);
  }

  // Ensure target directories exist
  ensureDir(TARGET_SRC_DIR);
  ensureDir(TARGET_DIST_DIR);

  // Copy files to src
  for (const file of FILES_TO_COPY) {
    const src = path.join(SOURCE_DIR, file);
    const destSrc = path.join(TARGET_SRC_DIR, file);
    const destDist = path.join(TARGET_DIST_DIR, file);
    copyFile(src, destSrc);
    copyFile(src, destDist);
  }

  // Generate index.ts for src
  generateIndex();

  // Also copy index.js to dist (compile index.ts inline)
  const distIndexJs = `/**
 * Convex API types for CLI (compiled)
 * @module
 */
export { api } from './api.js';
`;
  fs.writeFileSync(path.join(TARGET_DIST_DIR, 'index.js'), distIndexJs);
  console.log(`✅ Generated: packages/cli/dist/convex-api/index.js`);

  // Copy index.ts to index.d.ts for dist
  const srcIndexTs = fs.readFileSync(path.join(TARGET_SRC_DIR, 'index.ts'), 'utf-8');
  fs.writeFileSync(path.join(TARGET_DIST_DIR, 'index.d.ts'), srcIndexTs);
  console.log(`✅ Generated: packages/cli/dist/convex-api/index.d.ts`);

  console.log('');
  console.log('✨ Sync complete!');
  console.log('');
}

// Run sync
sync();
