/**
 * Agent Prompt Generator (Webapp Display Version)
 *
 * Simplified version for UI display purposes only.
 * The authoritative prompts are generated by the backend.
 * This is kept for backward compatibility with UI components.
 */

import { composeSystemPrompt } from '../../../generator.js';
import { getCliEnvPrefix } from '../utils/env';

export interface PromptContext {
  chatroomId: string;
  role: string;
  teamId?: string;
  teamName: string;
  teamRoles: string[];
  teamEntryPoint?: string;
  /** The Convex URL being used. If non-production, CLI commands will include env var override. */
  convexUrl?: string;
}

/**
 * Generate a full agent initialization prompt for UI display.
 * Delegates to composeSystemPrompt() to ensure custom agents receive
 * the same complete prompt as remote agents (classification guide,
 * role workflow, commands reference, etc.).
 */
export function generateAgentPrompt(context: PromptContext): string {
  const { chatroomId, role, teamId, teamName, teamRoles, teamEntryPoint, convexUrl } = context;
  return composeSystemPrompt({
    chatroomId,
    role,
    teamId,
    teamName,
    teamRoles,
    teamEntryPoint,
    convexUrl: convexUrl ?? '',
    agentType: 'custom',
  });
}

/**
 * Generate a short prompt for display in limited space
 */
export function generateShortPrompt(context: PromptContext): string {
  const { chatroomId, role, convexUrl } = context;
  const prefix = getCliEnvPrefix(convexUrl);
  return `${prefix}chatroom context read --chatroom-id="${chatroomId}" --role="${role}" && ${prefix}chatroom get-next-task --chatroom-id="${chatroomId}" --role="${role}"`;
}
