/**
 * Agent Prompt Generator (Webapp Display Version)
 *
 * Simplified version for UI display purposes only.
 * The authoritative prompts are generated by the backend.
 * This is kept for backward compatibility with UI components.
 */

import { getRoleTemplate } from './templates';
import { getCliEnvPrefix } from '../utils/env';

export interface PromptContext {
  chatroomId: string;
  role: string;
  teamName: string;
  teamRoles: string[];
  teamEntryPoint?: string;
  /** The Convex URL being used. If non-production, CLI commands will include env var override. */
  convexUrl?: string;
}

/**
 * Generate a simplified agent initialization prompt for UI display
 * Note: This is a simplified version. The CLI fetches the full prompt from the backend.
 */
export function generateAgentPrompt(context: PromptContext): string {
  const { chatroomId, role, teamName, teamRoles, convexUrl } = context;
  const template = getRoleTemplate(role);
  const cliEnvPrefix = getCliEnvPrefix(convexUrl);

  return `# ${teamName} Team

## Your Role: ${template.title.toUpperCase()}

${template.description}

**Responsibilities:**
${template.responsibilities.map((r) => `- ${r}`).join('\n')}

## Getting Started

Run this command to join the chatroom:

\`\`\`bash
${cliEnvPrefix}chatroom wait-for-task ${chatroomId} --role=${role}
\`\`\`

The CLI will fetch the complete initialization prompt from the backend with:
- Detailed workflow instructions
- Command examples
- Role-specific guidance
- Team collaboration patterns

## Team Roles

${teamRoles.join(', ')}

## Next Steps

1. Copy the command above
2. Run it in your terminal
3. Follow the detailed instructions provided by the CLI
`;
}

/**
 * Generate a short prompt for display in limited space
 */
export function generateShortPrompt(context: PromptContext): string {
  const { chatroomId, role, convexUrl } = context;
  const prefix = getCliEnvPrefix(convexUrl);
  return `${prefix}chatroom wait-for-task ${chatroomId} --role=${role}`;
}
