/**
 * Agent Prompt Generator (Webapp Display Version)
 *
 * Simplified version for UI display purposes only.
 * The authoritative prompts are generated by the backend.
 * This is kept for backward compatibility with UI components.
 */

import { getRoleTemplate } from './templates.js';
import { getContextGainingGuidance } from '../../shared/getting-started-content.js';
import { getCliEnvPrefix } from '../utils/env.js';

export interface PromptContext {
  chatroomId: string;
  role: string;
  teamName: string;
  teamRoles: string[];
  teamEntryPoint?: string;
  /** The Convex URL being used. If non-production, CLI commands will include env var override. */
  convexUrl?: string;
}

/**
 * Generate a simplified agent initialization prompt for UI display
 * Note: This is a simplified version. The CLI fetches the full prompt from the backend.
 */
export function generateAgentPrompt(context: PromptContext): string {
  const { chatroomId, role, teamName, teamRoles, convexUrl } = context;
  const template = getRoleTemplate(role);

  // Use shared getting started content
  // convexUrl should be provided by webapp, but fallback to empty string for type safety
  // Webapp prompts always use 'custom' type since users copy these prompts
  // to paste into their own agents (which are custom/manually-started)
  const gettingStarted = getContextGainingGuidance({
    chatroomId,
    role,
    convexUrl: convexUrl ?? '',
    agentType: 'custom',
  });

  return `# ${teamName} Team

## Your Role: ${template.title.toUpperCase()}

${template.description}

**Responsibilities:**
${template.responsibilities.map((r) => `- ${r}`).join('\n')}

${gettingStarted}

## Team Roles

${teamRoles.join(', ')}

## Next Steps

1. Run the **register-agent** command above to register your agent type
2. Copy the **context read** command to review conversation history
3. Run **wait-for-task** to receive your first task
4. Follow the detailed instructions provided by the CLI
`;
}

/**
 * Generate a short prompt for display in limited space
 */
export function generateShortPrompt(context: PromptContext): string {
  const { chatroomId, role, convexUrl } = context;
  const prefix = getCliEnvPrefix(convexUrl);
  return `${prefix}chatroom context read --chatroom-id=${chatroomId} --role=${role} && ${prefix}chatroom wait-for-task --chatroom-id=${chatroomId} --role=${role}`;
}
